codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false

coverage:
  precision: 2
  round: down
  range: 60...85

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        enabled: yes
        target: 1
        threshold: 0.1
    patch:
      default:
        enabled: off

ignore:
  - "**/*.ipynb"
  - docs
  - deps
  - data
  - docker
  - .github
  - .git