name: CI-examples

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  # Trigger the workflow on push to master or pull request
  # to be merged in master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  list-examples:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout JUDI
        uses: actions/checkout@v3

      - id: set-matrix
        run: echo "matrix=$(ls examples/scripts/*.jl examples/machine-learning/*.jl | xargs -n 1 | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash

  run-examples:
    runs-on: ubuntu-latest
    needs: list-examples
    name: ${{ matrix.example }} on Julia ${{ matrix.version }}

    env:
      DEVITO_ARCH: gcc-9
      DEVITO_LANGUAGE: "openmp"
      DEVITO_LOGGING: "ERROR"
      OMP_NUM_THREADS: 1
      NITER: 2

    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJson(needs.list-examples.outputs.matrix) }}
        version: ['1.8']

        include:
         - example: "examples/scripts/modeling_basic_2D.jl"
           version: '1.6'

         - example: "examples/scripts/modeling_basic_2D.jl"
           version: '1.7'

    steps:
      - name: Checkout JUDI
        uses: actions/checkout@v3

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: x64

      - name: Set julia python
        run: |
          python3 -m pip install -U pip
          python3 -m pip install matplotlib seiscm colorcet
          PYTHON=$(which python3) julia -e 'using Pkg;Pkg.add("PyCall");Pkg.build("PyCall")'

      - name: Build JUDI
        uses: julia-actions/julia-buildpkg@latest

      - name: Install packages
        run: |
          julia -e 'using Pkg;Pkg.add(["NLopt", "Flux", "JOLI", "PyPlot", "Zygote", "IterativeSolvers", "SlimOptim", "HDF5", "SegyIO", "SetIntersectionProjection"])'
          julia -e 'using Pkg;Pkg.add(url="https://github.com/slimgroup/SlimPlotting.jl")'
          julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'

      - name: Run examples
        run: julia -p 2 -t 1 ${{ matrix.example }}
